### ISSUE TITLE
Windows10 下无法运行

### ISSUE THREAD

**Issue by YJZoier** [memset0/luogu-todolist#11]
RT，难道是我环境的问题？百度了一下好像是编码的问题，但是我不是很懂 *Python*
```
Traceback (most recent call last):
  File "E:\桌面\luogu-todolist\host.py", line 1, in <module>
    import spider, webserver
  File "E:\桌面\luogu-todolist\spider.py", line 108, in <module>
    update()
  File "E:\桌面\luogu-todolist\spider.py", line 88, in update
    titleList = yaml.load(open('cache/title.yml', 'r+').read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 28: illegal multibyte sequence
```

**Comment by memset0** [comment]
是的，我的锅 ...

**Comment by YJZoier** [comment]
其实 Pull Request 里有修复后的版本
本来的 CSS 好像被墙了（我是中国电信，浙江），百度里有镜像，实测 `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.3.0/material.teal-red.min.css">` 可用

**Comment by memset0** [comment]
> @YJZoier 
> 其实 Pull Request 里有修复后的版本
嗯，但是 merge 那份过于麻烦 QAQ 
> 本来的 CSS 好像被墙了（我是中国电信，浙江），百度里有镜像，实测 `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.3.0/material.teal-red.min.css">` 可用
我也是浙江的中国电信用户，实测那个 cdn 有时可用有时不可以用。不知道什么鬼 = =

**Comment by luoguyuntianming** [comment]
请问各位有更好的解决方案吗？我试了都不行233

**Comment by YJZoier** [comment]
@luoguyuntianming 

> 请问各位有更好的解决方案吗？我试了都不行233

好像 memset0 已经开始更新了，这是一个临时解决方案：<https://github.com/YJZoier/luogu-todolist>

**Comment by memset0** [comment]
emm ... 我手头没有 windows 所以也不方便测试 ...
由于个人学业原因省选前这个项目可能不会再更新了 ...

抱歉
